language: node_js
version: 1.0
node_js:
- node
install:
- yarn
cache:
  yarn: true
  directories:
  - node_modules
jobs:
  include:
  - stage: lint
    script: yarn lint
  - stage: test
    script: yarn test:cov
  - stage: build
    script: yarn build
    deploy:
      provider: npm
      email: tanfonto@pm.me
      tag: latest
      skip_cleanup: true
      edge: true
      on:
        tags: true
      api_key: 
        secure: KMuM+r59E0inClpBxiI0B7GKO+nuTlX+zycJw5yCHzCsEyVExw29+nlIBbENcLEoocRW3Xg2KK7msOwEghc5P7Zbwp7OICHnKDUJ02tW7UNsQTlrqvQW0PHjGH5kEK3hPSNdN9oT2adHeSi2skSHiQuv/KWF16AI28jFi8rm4iH2oNonPHC5HUCGgRDJF3meGQ0y8ikMrkWf7xyNEP1UUEpzaMlRNJ0M6PGRuDZy88fZ0H7WkdhTinyLIIz3rOwSCRrvId1N2RH1kdr35L3qwTb1d18pCLQQx/2ECCMjQKSwRYSVtKVCSwgIdzOa90hZF9/1mrZjDeM0lCdrJwh/tf/t97vtosZMChccvfULXUUbKIaUj/Uz2vsB0v/WZlaRWTObIrg3N9M+wqcGPphERI6cbY/mRtb+Dr5UI+HcMUyqrhYiNBIBzp+FAambyUpS+xRdGnUZ7mGWvkKUGLFX89Mzu/kTzaiaDTfOVeA3Z9V2Sj6vvrSYxR1dNus70vbz7pyGs47i2r+bgm9msVg1DMDacbgrHTJBZzvwZ9zqeLDkxytMIaKt3p6WLnm2FVIx5ORF/psr7i0yrb9xO4J4MdAzXxU9nlqziBuOj2NTsADP93W3k5DDY/4ve2SPsyhXWrUMwQr6aP9WysG8jvJYcFZVP7Kkp6qfc3SMdOc0dVI=
