language: node_js
version: 1.0
node_js:
- node
install:
- yarn
cache:
  yarn: true
  directories:
  - node_modules
jobs:
  include:
  - stage: lint
    script: yarn lint
  - stage: test
    script: yarn test:cov
  - stage: build
    script: yarn build
    deploy:
      provider: npm
      email: tanfonto@pm.me
      tag: latest
      skip_cleanup: true
      edge: true
      on:
        tags: true
      api_key:
        secure: E1i/FphsOLGXtygQ1hLsizywZEFXghmPHSLQ02C1XgkuLWjv/YfBdEPtzeAL2zPgVJobk8cKuErMcflPNAm4fDhXpL1csPf5AxOjIVDN5HDmGOfpOR+PPdXg/by+hHIcFRq4OhvCxzIIOX4OAbouH2kT3hK6bHK/f8ezDIFWdkr/f13HpJ4gUBkRReKh2pFHvf1I5mxrT+DZyMAMNf+fII0pF79GEGd1/HrlPzv1RE1UsJ2zQZj3EEJ0fTEx1U46F9blB5goYk1EWTpcJuxFzGpVIHeJ00pEQmWr+Iyd3BFepyd0Lx3Z09xIfcMg01GKdRCAmNPwaVA+PmHDbpn7izsQY1S736+ESB7b8l/3EFArSrssmvxj5VTp4S/VTv+f+iur2tjlL3k07j1H9y2UamfpLEzbAR4aeWwiVX9zWf0odSm/7uTggODRxvwQO2gYECyvF+uBBqOTjFwjGsArod5qzKxjA+PB6qvlcdpck25ZiqTrHJ9liEwpNijgt0oiD+aeMk3hiKPvYf0oogH4jdWQJjdHBeFQz9nywvdVqcHUCe6VG7devvHOCwNcK5YPrrMhNxVq4aYJP7DjG0lED0QLF1ijStl1g73H+OE70JAlpCV7P/PLrAFdrQ83y7wvhztsPcZguNM9x9g4ZvIFNrx65PGFZftlymdzcioTkMA=

